version: '3'

services:
  web:
    container_name: web
    build:
      context: apps/sveltekit/
      dockerfile: Dockerfile
      args:
        - APP_URL=${APP_URL}
        - DATABASE_URL=${DATABASE_URL}
        - SMTP_HOST=${SMTP_HOST}
        - SMTP_PORT=${SMTP_PORT}
        - SMTP_USERNAME=${SMTP_USERNAME}
        - SMTP_PASSWORD=${SMTP_PASSWORD}
        - GITHUB_CLIENT=${GITHUB_CLIENT}
        - GITHUB_SECRET=${GITHUB_SECRET}
        - GOOGLE_CLIENT=${GOOGLE_CLIENT}
        - GOOGLE_SECRET=${GOOGLE_SECRET}
        - SECRET_KEY=${SECRET_KEY}
        - PEPPER=${PEPPER}
        - EXCHANGE_RATE_API_KEY=${EXCHANGE_RATE_API_KEY}
        - CRON_JOB_SECRET=${CRON_JOB_SECRET}
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ORIGIN=${ORIGIN}
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:14-alpine
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_DB}

  proxy:
    container_name: proxy
    build:
      context: apps/nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  postgres_data:
