version: '3'

services:
  db:
    image: postgres:14-alpine
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - dev_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_DB}

volumes:
  dev_db:
